# AWS_REGION := eu-central-1
# ECR_REPOSITORY_URI := 565802942559.dkr.ecr.eu-central-1.amazonaws.com
# IMAGE := hypersafe-backend

build:
	tsc 

# build:
# 	docker build --no-cache -t ${IMAGE} .

# run:
# 	docker run -p 8080:8089 ${IMAGE}